### ISSUE TITLE
Python + Selenium + Ubuntu Server でブラウザ操作がしたい

### ISSUE THREAD

**Issue by noraworld** [noraworld/scraps#1]
# Python を選んだ理由
"Selenium" で検索すると Python の記事ばかりヒットするため。ヒットする記事が多い言語のほうが躓いたときに解決しやすくて良いかなと思って。

でも、なんで Python の記事が多いんだろうな。スクレイピング = Python みたいな定説があるんだろうか。ブラウザ操作を行うので、個人的には Node.js のほうが親和性が高そうで良いんじゃないかなと思っているんだけど。

**Comment by noraworld** [comment]
このへんを参考にしてみている。

* [JavaScriptを書ける人であれば誰でもスクレイピングはできるよっていう話](https://qiita.com/centerfield77/items/425780a673568d3008e6)
* [10分で理解する Selenium](https://qiita.com/Chanmoro/items/9a3c86bb465c1cce738a)
* [EC2 UbuntuでGoogle Chromeをヘッドレス実行してスクリーンショットを採取する手順](https://qiita.com/shinsaka/items/37436e256c813d277d6d)

**Comment by noraworld** [comment]
Selenium を使えば、Web ページ内の JavaScript を解釈して、特定のボタンをクリックしたりできそう。

[Seleniumからクリックができない...そうだ、JSからクリックしよう](https://yuta0306.github.io/selenium-click-by-js)

**Comment by noraworld** [comment]
とりあえず Selenium のサンプルコードみたいなのを実行してみたらエラー。

```shell
pipenv run python app.py
```

```
Connecting to remote browser...
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/attendance-xoWXRqd6/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 7, in <module>
    driver = webdriver.Chrome(options = options)
  File "/home/ubuntu/.local/share/virtualenvs/attendance-xoWXRqd6/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/ubuntu/.local/share/virtualenvs/attendance-xoWXRqd6/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 90, in __init__
    self.service.start()
  File "/home/ubuntu/.local/share/virtualenvs/attendance-xoWXRqd6/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
```

もしかして Selenium だけじゃなくて `chromedriver` もインストールしないといけないのか？

**Comment by noraworld** [comment]
いろいろ調べたら、Google Chrome と `chromedriver` もインストールしないといけない模様。Selenium はあくまでブラウザ操作を行うためのライブラリで、ブラウザが内蔵されているわけではない。

そのため、Google Chrome をインストールしようとしたのだが、まさかの ARM (Raspberry Pi) 版がないらしい。

https://askubuntu.com/questions/1191260/how-do-i-install-google-chrome-on-raspberry-pi-4-running-ubuntu-19-10

以下の記事を試してみたが、両方ともダメだった。

* https://skolo.online/documents/webscrapping/
* https://self-development.info/ubuntu%E3%81%A7selenium%E3%82%92%E5%8B%95%E3%81%8B%E3%81%97%E3%81%A6%E3%82%B9%E3%82%AF%E3%83%AC%E3%82%A4%E3%83%94%E3%83%B3%E3%82%B0%E3%82%92%E8%A1%8C%E3%81%86%E3%80%90python%E3%80%91/

**Comment by noraworld** [comment]
https://askubuntu.com/questions/1191260/how-do-i-install-google-chrome-on-raspberry-pi-4-running-ubuntu-19-10 にも書いてあったが、Raspberry Pi では代わりに Chromium をインストールすれば良いらしい。

以下の記事が参考になった。

https://irukanobox.blogspot.com/2021/02/raspberry-pipythonselenium.html

無事、実行できるようになった。

**Comment by noraworld** [comment]
ログイン先でブラウザ操作がしたいのだが、クッキーを入れてアクセスしてもログイン後の HTML が取得できていない。

クッキーの情報が間違っているのか、それともクッキーではログイン後の情報を取得できないのか。

https://www.selenium.dev/ja/documentation/webdriver/browser/cookies/

**Comment by noraworld** [comment]
`XPATH` の指定が間違っているという可能性もある。

* https://selenium-python.readthedocs.io/locating-elements.html
* https://qiita.com/yutaiii/items/0be6671fbaea842d9a38

Selenium IDE というのを試してみた。

* https://doradorasuki.hatenablog.com/entry/2019/09/16/235140
* https://www.selenium.dev/selenium-ide/

ログイン前にもある DOM は取得できるのだが、やはりログイン後の DOM が取得できないので、ログインできていない可能性のほうが高い。

**Comment by noraworld** [comment]
現在は Raspberry Pi 上で検証しているのだが、やはり画面がないとわかりづらいので、Mac で試してみることにする。

ここらへんを参考にして Mac でも動くようにする。

https://www.tutorialspoint.com/how-to-install-selenium-webdriver-on-mac-os

**Comment by noraworld** [comment]
上記のサイトの記事に従い `chromedriver` をインストールして、`options.add_argument('--headless')` を消したら、ヘッドレスではなくブラウザで開くようになった。

やはりログイン前の画面だった。

**Comment by noraworld** [comment]
クッキーを入れなくても、ログイン画面に ID とパスワードを入れれば良いのか。

**Comment by noraworld** [comment]
ID とパスワードを入力して submit ボタンを押したらログイン後の画面にアクセスできるようになった。

https://prcmyself.com/selenium-for-text-input-and-deletion-of-input-forms

**Comment by noraworld** [comment]
ただ、ログイン後の DOM にアクセスしようとするとエラーになった。その原因として、ログインされる前に DOM を取得しようとしてしまっているのではないかということに気づき、5 秒待ってから DOM を取得するようにしてみたら、見事、ログイン後の DOM を取得できるようになった 🎉 

ちなみに 5 秒待つというのは、先ほど Raspberry Pi に Chromium をインストールする手順で参考になったサイトがまたまた参考になった。

https://irukanobox.blogspot.com/2021/02/raspberry-pipythonselenium.html

**Comment by noraworld** [comment]
というか、最初はなんで無理やりクッキーを埋め込んでログインしようとしていたんだろうな。

**Comment by noraworld** [comment]
ID とパスワードをコード内にそのまま書くのはさすがにやばすぎるので、環境変数から読み込むようにした。以下の記事を参考にした。

* https://dev.to/jakewitcher/using-env-files-for-environment-variables-in-python-applications-55a1
* https://qiita.com/harukikaneko/items/b004048f8d1eca44cba9

**Comment by noraworld** [comment]
ログイン後、目的の要素をクリックすると以下のようなエラーが発生した。

```
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="xxx">...</div> is not clickable at point (xxx, xxx). Other element would receive the click: <div id="xxx" class="xxx">...</div>
```

いろいろ読んだけど、やり方わからず or 解決せず。

* https://yoshikiito.net/blog/archives/731/
* https://qiita.com/DNA1980/items/528ff6269986b262acdc
* https://hacknote.jp/archives/23286/

ところが、クリックしたい要素の指定の仕方を変える (`XPATH` の値を変更する) ことでクリックできるようになった 🎉

**Comment by noraworld** [comment]
これが参考になった。

https://www.soudegesu.com/en/post/python/selenium-element-selector/

`class` のように複数ある要素に対しては `[1]` のように配列の添字のような指定をすることで特定の要素を指定することができるようになる。`[0]` からではなく `[1]` かららしい。

**Comment by noraworld** [comment]
プログラムの最後で `driver.quit()` を実行しているが、途中で例外が発生した場合は呼ばれないんじゃないのかなとふと思った。

それで、プロセスを見てみたら、めっちゃゴミが溜まっていた。案の定、例外が発生するとブラウザが正常に閉じられていないようだ。

```shell
ps aux | grep -ci chrome
167
```

下記の記事にあるように、例外を捕捉して、どんな場合でも `driver.quit()` が呼ばれるようにしたほうが良さそう。

https://scrapbox.io/kb84tkhr-pub/Selenium_-_%E3%81%8B%E3%81%AA%E3%82%89%E3%81%9Awebdriver%E3%82%92%E9%96%89%E3%81%98%E3%82%8B

**Comment by noraworld** [comment]
思い返せば、ヘッドレスではなくアプリとして起動したときも、正常に最後まで動作したときは勝手にブラウザが閉じたのに、例外が発生したときはブラウザが開いたままだった。
